# ----- SAHI AUR PROFESSIONAL APPROACH -----
- name: Configure Web Servers (Nginx and Apache)
  hosts: all
  become: yes
  
  roles:
    - nginx   # Role sirf installation aur config ke liye
    - apache  # Role sirf installation aur config ke liye

  post_tasks: # Yeh tasks hamesha roles ke baad chalte hain
    - name: Ensure Nginx is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Ensure Apache is running and enabled
      ansible.builtin.service:
        name: "{{ 'httpd' if ansible_facts['os_family'] == 'RedHat' else 'apache2' }}"
        state: started
        enabled: yes